name: CI - Migration Checks

on:
  pull_request:
    branches: [main]
    paths:
      - 'migrations/**'
      - 'flyway.toml'

jobs:
  checks:
    uses: ./.github/workflows/zzz-checks.yml
    with:
      target-environment: staging
      database-name: FlywaySample_Staging
      environment: ci
    secrets:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
