name: Deploy to Dev

on:
  push:
    branches: [main]
    paths:
      - 'migrations/**'
      - 'flyway.toml'

jobs:
  checks:
    uses: ./.github/workflows/zzz-checks.yml
    with:
      target-environment: dev
      database-name: FlywaySample_Dev
      environment: dev-read-only
    secrets:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}

  deploy:
    needs: checks
    uses: ./.github/workflows/zzz-deploy.yml
    with:
      target-environment: dev
      database-name: FlywaySample_Dev
      environment: dev
    secrets:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
