name: Deploy to Staging

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Dev"]
    types: [completed]

jobs:
  checks:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/zzz-checks.yml
    with:
      target-environment: staging
      database-name: FlywaySample_Staging
      environment: staging-read-only
    secrets:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}

  deploy:
    needs: checks
    uses: ./.github/workflows/zzz-deploy.yml
    with:
      target-environment: staging
      database-name: FlywaySample_Staging
      environment: staging
    secrets:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
