name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    env:
      BUILD_DATABASE_PASSWORD: ${{ secrets.BUILD_DATABASE_PASSWORD }}
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: ${{ secrets.BUILD_DATABASE_PASSWORD }}
        ports:
          - 1433:1433
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Flyway Enterprise
        uses: red-gate/setup-flyway@v3
        with:
          edition: enterprise
          i-agree-to-the-eula: true
          email: ${{ secrets.FLYWAY_EMAIL }}
          token: ${{ secrets.FLYWAY_TOKEN }}

      - name: Setup demo environment
        uses: ./.github/actions/setup-demo
        with:
          sqlserver-container-id: ${{ job.services.sqlserver.id }}
          database-name: FlywaySample_Staging
          create-build-db: "true"
          working-directory: flyway

      - name: Run pre-deployment checks
        uses: red-gate/flyway-actions/migrations/checks@sarif-code-scanning-upload
        with:
          target-environment: staging
          target-password: ${{ secrets.STAGING_DATABASE_PASSWORD }}
          build-environment: build
          build-password: ${{ secrets.BUILD_DATABASE_PASSWORD }}
          build-ok-to-erase: true
          working-directory: flyway

      - name: Deploy migrations
        uses: red-gate/flyway-actions/migrations/deploy@sarif-code-scanning-upload
        with:
          target-environment: staging
          target-password: ${{ secrets.STAGING_DATABASE_PASSWORD }}
          working-directory: flyway
